[bugfix] Update constants.typoscript
benjaminkott/bootstrap_package pull request #943
Opened 2020-10-28 17:26 UTC by JPDesign

# Pull Request

## Related Issues

* Closes #
* Fixes # [bug]
* Resolves # [feature/question]

## Prerequisites

* [ ] Changes have been tested on TYPO3 v8.7 LTS
* [ ] Changes have been tested on TYPO3 v9.5 LTS
* [ ] Changes have been tested on TYPO3 dev-master
* [ ] Changes have been tested on PHP 7.0.x
* [ ] Changes have been tested on PHP 7.1.x
* [ ] Changes have been tested on PHP 7.2.x
* [ ] Changes have been checked for CGL compliance `php-cs-fixer fix`

## Description

Do not overwrite 005_relatedVideos with 005_modestbranding.

## Steps to Validate 

1. [First Step]
2. [Second Step]
3. [and so on...]

2020-11-13 11:25 UTC, gilbertsoft commented
Thanks for your PR. Well, actually this is not a bug but a typo. Your change will not fix a wrong behavior but the ordering of the constants in the constant editor. There are also similar problems which should also be addressed with this patch, can you please check everything and add more commits.

2020-11-14 09:42 UTC, gilbertsoft requested changes

2020-11-14 09:42 UTC, gilbertsoft commented on Configuration/TypoScript/ContentElement/constants.typoscript
>              # cat=bootstrap package: content elements/131_contentelement/005_relatedVideos; type=boolean; label=Related Videos
Number should be unique, 006 on this line

2020-11-14 09:42 UTC, gilbertsoft commented on Configuration/TypoScript/ContentElement/constants.typoscript
> +            # cat=bootstrap package: content elements/131_contentelement/005_modestbranding; type=boolean; label=Modest Branding
Number should be 007 on this line

2023-04-25 15:28 UTC, benjaminkott commented
seems to be resolved with https://github.com/benjaminkott/bootstrap_package/commit/6e8c4a59a8ad934810b8cfab35824e163af93cfd

2023-04-25 15:28 UTC, closed without merging