[FEATURE] Maintain page layout variants in structure elements
benjaminkott/bootstrap_package pull request #957
Opened 2020-11-20 09:23 UTC by buepro

# Pull Request

## Related Issues

* Resolves #956 

## Prerequisites

* Changes have been tested on TYPO3 v10.4 LTS

2020-11-20 10:02 UTC, gilbertsoft requested changes
Thanks for you proposition. Currently there are some open questions, most important is the register usage which is absolute unclear to me how this should work as no LOAD_REGISTER and RESTORE_REGISTER is used and I do not see on which calls this does relay. This must be visible and clear from the code, to be honest currently it looks more like russian roulette.

2020-11-20 11:30 UTC, buepro commented on Configuration/TypoScript/Helper/Register.typoscript
> +lib.register = TEXT
It could be `lib.bpRegister` or `lib.bootstrapPackageRegister`

2020-11-20 11:30 UTC, buepro commented on Configuration/TypoScript/Helper/Register.typoscript
> +    wrap = {REGISTER:|}
It is loaded in [lib.dynamicContent](https://github.com/benjaminkott/bootstrap_package/blob/34fc1bd9ce09b56e1e8581c5475c10a5fff272b1/Configuration/TypoScript/ContentElement/Helper/DynamicContent.typoscript#L52).

2020-12-05 12:27 UTC, gilbertsoft commented
Short update: I didn't forget your PR here but had no time so far to finish it. Main problem currently is the register part which is imho not a clean solution. If I have to ask where that register is saved the code is not clear enough and that's a no go. The fix it self is fine and it also seems to work. I already did some additional tests to find a cleaner solution but as said I've no time left currently to finish it. Maybe you have an idea on how to solve it in a more clean way.

2020-12-13 10:32 UTC, buepro commented
What do you think about passing the colPos information in `lib.contentElement` eliminating the need for `lib.bpRegister`:

```
lib.contentElement {
   ...
    variables {
        ...
        backendLayoutColPos = TEXT
        backendLayoutColPos.data = register:colPos
    }
   ...
```

And then using it in the layout:

`<f:variable name="columnConfig">{backendlayoutConfig.{pageLayoutColPos}}</f:variable>`

2021-08-16 10:31 UTC, benjaminkott commented
@buepro we added support for ext:container with the latest release that also handles the size calculation for images.

please check https://github.com/benjaminkott/bootstrap_package/pull/1035 and open an issue if this does not suit your needs.

2021-08-16 10:31 UTC, closed without merging