Make bootstrap package availible for first release of TYPO3 11
benjaminkott/bootstrap_package pull request #971
Opened 2021-02-14 10:09 UTC by linawolf

The requirements still only allow "11.*.*@dev" even though there is the release

2021-02-14 10:27 UTC, jonaseberle approved these changes

2021-02-19 19:20 UTC, gilbertsoft commented
Thanks for your PR. I'm preparing this since months see https://github.com/benjaminkott/bootstrap_package/pull/911.

2021-03-21 11:06 UTC, jonaseberle requested changes
`^11.0 || ^11.1` is superfluous since one is a subset of the other.
The `11.*.*@dev`  should be kept to allow using it with non-released versions.

2021-08-14 09:23 UTC, linawolf commented
It is availible now, So this PR can be closed

2021-08-14 09:23 UTC, closed without merging